In [1]:
import pandas as pd

In [2]:
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [19]:

temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [15]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,32.8997,8.715,29827
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,34.6298,8.700,22523
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,17.1064,8.571,13632
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,14.7781,8.566,17154
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,14.8697,8.556,9776

In [22]:
temp_df = pd.DataFrame()

In [23]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,32.8997,8.715,29827
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,34.6298,8.700,22523
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,17.1064,8.571,13632
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,14.7781,8.566,17154
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,14.8697,8.556,9776
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,21.0908,8.534,18004
6,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,26.1735,8.527,35251
7,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,6.2220,8.518,4562
8,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,18.9930,8.505,18903
9,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,23.7994,8.494,26095
10,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,23.1796,8.493,20201
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,20.9811,8.486,29762
12,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,19.5159,8.500,12316
13,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,43.6428,8.468,38987
14,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,13.4305,8.468,9448
15,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,23.0911,8.462,29309
16,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,22.1178,8.452,14059
17,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,7.2436,8.451,4125
18,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0091,8.444,6376
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,8.5971,8.440,13820

In [ ]:
# Initialize an empty DataFrame outside the loop to store all results
temp_df = pd.DataFrame()

for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    
    temp_df = pd.concat([temp_df, df], ignore_index=True)

In [ ]:
df()

In [ ]:
df.shape

In [ ]:

df.to_csv('movies.csv')