In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)

In [4]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
#lookup table

In [6]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [7]:
py=9/14
pn=5/14

In [8]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [10]:
#Outlook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
Pon=0
Prn=2/5
Psn=3/5
Poy=4/9
Pry=3/9
Psy=2/9

In [17]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [18]:
PCN=1/5
PHN=2/5
PMN=2/5
PCY=3/9
PHY=2/9
PMY=4/9

In [20]:
#humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [21]:
phn=4/5
pnn=1/5
phy=3/9
pny=6/9

In [22]:
#wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [23]:
PstrNO=3/5
PweakNO=2/5
PstrYES=3/9
PweakYES=6/9

In [25]:
#QUESTION OUTLOOK=SUNNY,TEMP=HOT,HUMIDITY=HIGH,WIND=WEAK
Pyes = py*Psy*PHY*phy*PweakYES
print(Pyes)

0.007054673721340388

In [27]:
Pno=pn*Psn*PHN*phn*PweakNO
print(Pno)

0.02742857142857143

In [29]:
#no play is answer